version: '3'
services:
  site:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    networks:
      - jekyll-net

networks:
  jekyll-net:

volumes:
  bundle_cache:
